### ISSUE TITLE
Tortoise TTS and  Audiocraft incompatible

### ISSUE THREAD

**Issue by 78Alpha** [rsxdalv/tts-generation-webui#130]
Audiocraft 1.0.0 requires transformers 4.31.0, however, Tortoise TTS only works with 4.29.2 due to a regression in 4.31.0 that makes it throw an unexpected keys error.

In order to get the tortoise code to run I had to comment a couple lines as well.
```
#tokenizer_vocab_file=tokenizer_path,
#tokenizer_basic=tokenizer_basic,
```
Due to tortoise not using these.
`TypeError: TextToSpeech.__init__() got an unexpected keyword argument 'tokenizer_vocab_file'`

**Comment by rsxdalv** [comment]
It seems that my tortoise patch had issues. Did you have the webui installed before? Then I need to bump up the version of tortoise to force the reinstall.

**Comment by 78Alpha** [comment]
Yes, I had it installed before. I usually download the new zip and reinstall from that. I looked at the latest version of tortoise and didn't see any mention of the tokenizer_vocab_file. I'm going to try to update it again, a full fresh install.

**Comment by 78Alpha** [comment]
After manually installing tortoise from github and install pytorch with cuda support, it seems to be fine.

Previously I would use the update.py but it seemed to miss some things. I changed to downloading a zip and install the requirements files, but it seems tortoise never got updated.

I'll mark this as closed. Tortoise test audio generated and audiogen produced a sound file as well on the same install.

**Comment by rsxdalv** [comment]
Thank you for your time!

What I'll do is add the latest tortoise updates, and I'll also merge the vocab file into main. This repo uses my fork or Tortoise which is almost the same but a little bit different. Then I'll bump the version, which will make the update.py work correctly.
